name: Deploy App

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          APP_DIR=$HOME/${{ secrets.APP_DIR }}
          cd $APP_DIR
          LOG_FILE="$APP_DIR/deployment_$(date '+%Y-%m-%d_%H-%M-%S').log"
          {
            git pull origin main &&
            composer install &&
            composer update &&
            php artisan migrate &&
            php artisan route:clear &&
            php artisan route:cache &&
            php artisan view:clear &&
            php artisan view:cache &&
            php artisan config:cache &&
            php artisan config:clear &&
            php artisan cache:clear
          } > $LOG_FILE 2>&1 || {
            echo "An error occurred during deployment. See $LOG_FILE for details."
          }
